### ISSUE TITLE
Plugin does not work on ReactNative version >= 0.39.0

### ISSUE THREAD

**Issue by TSMMark** [eteeselink/babel-plugin-transform-class-display-name#1]
Try it and see.

**Comment by eteeselink** [comment]
Hey! Thanks for your comment.

I don't currently use React Native for anything, so "try it and see" amounts to "set up and learn a whole React Native dev environment", which I don't have time for.

However, I'd be happy to accept a pull request that fixes this. Do you have any idea where it goes wrong? Do you know whether it worked on earlier versions of React Native?

**Comment by TSMMark** [comment]
Hi, yes, sorry I should have been more detailed. It worked in React Native 0.38.x. Unfortunately, I have no idea where it is going wrong, as I am not very familiar with babel plugin architecture in general, and even less so with this specific plugin.

What I can say for sure is that after upgrading from 0.38 to 0.39, our react component classes no longer had the static property `displayName` at run time.

**Comment by eteeselink** [comment]
Impressive. In all honesty I have no good idea where to look. The RN changelog doesn't say anything about a change in how the react component base classes work or something.

You could help by making an example app of the tiniest possible RN application which exhibits this problem. I'm curious whether the babel *output* contains the displayName property correct in that setup, and whether it changed between RN 0.38 and 0.39. If there's no change there, then I'd wager there's no real bug in this plugin per se but RN does something to overwrite or remove the `displayName` property at runtime. 

If that's the case, maybe we can come up with a workaround.

**Comment by TSMMark** [comment]
I think making an example app of the tiniest possible RN application which exhibits this problem is a great idea, but unfortunately, I won't be able to get to this anytime soon.

**Comment by eteeselink** [comment]
Ok. I'll leave this issue open in case someone else gets in trouble because of this and has an idea. Thanks for reporting!

**Comment by eteeselink** [comment]
Closing this issue because of low activity. Feel free to reopen if you hit this too.
